#!/bin/sh

mkdir "$1"

sed 's/CHECKLIST/'"$1"'/g' $checklist_template >"$1/$1.mm"
sed 's/CHECKLIST/'"$1"'/g' $makefile_template >"$1/Makefile"
printf 'MAJOR=0\nMINOR=0\nPATCH=1\n' >"$1/version"
cp $macros "$1/"

       
