.# vim: ft=nroff
.TH mk-checklist 1 mk-checklist\- 0.0.1
.SH NAME
mk-checklist \- make a checklist
.SH SYNOPSIS
.B mk-checklist CHECKLIST
.SH DESCRIPTION
.B mk-checklist
generates a Makefile and template for a checklist. 
.SH OPTIONS
.TP 5
--help 
Print a brief usage message.
.SH EXAMPLES
.LP
.B mk-checklist newchecklist
.SH EXIT STATUS
exits non-zero on error.
.SH AUTHOR
Noah Birnel
.SH HISTORY
.SH FILES
.SH BUGS
Probably.
.SH SEE ALSO
.TP
.BR groff(1)
.TP
.BR groff_mm(7)
.TP
.IR "The Checklist Manifesto"
Atul Gawande 2009 Metropolitan Books
.SH LICENSE
Copyright 2014 Noah Birnel
.sp
MIT License

